import React, { Component } from "react";

export default function disclaimer() {
	return (
		<div id="copyright-disclaimer">
			<hr />
			<p>
				Created with{" "}
				<a href="https://reactjs.org/" target="_blank">
					ReactJS
				</a>
				,{" "}
				<a href="https://react-bootstrap.github.io/" target="_blank">
					React-Bootstrap
				</a>{" "}
				,{" "}
				<a href="https://github.com/axios/axios" target="_blank">
					Axios
				</a>{" "}
				and{" "}
				<a
					href="https://react-icons.github.io/react-icons/"
					target="_blank"
				>
					React-Icons
				</a>
				. Quiz questions are downloaded from the{" "}
				<a href="https://opentdb.com/" target="_blank">
					Open Trivia Database
				</a>
				, generated by its users. <br />
				Created by Mingrui Ma in March 2021. Source code can be found on
				<a href="#" target="_blank">
					GitHub
				</a>
				.
			</p>
			<hr />
		</div>
	);
}
